version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/maker-bundle
    versions:
    - 1.28.0
    - 1.29.1
    - 1.30.0
  - dependency-name: symfony/phpunit-bridge
    versions:
    - 5.2.1
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/web-server-bundle
    versions:
    - 4.4.18
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/validator
    versions:
    - 5.2.1
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/serializer
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/templating
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/google-mailer
    versions:
    - 5.2.2
    - 5.2.3
