version: "3.7"
services:
  mysql:
    image: mysql:8.0
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: altruisto

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - .:/var/www/html
    links:
      - mysql
    env_file:
      - .env
    user: 1000:1000
  composer:
    image: composer
    volumes:
      - .:/app
    command: install
  nginx:
    image: nginx:1.15.3-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 80:80
    restart: always
    depends_on:
      - php
      - mysql
  adminer:
    image: adminer
    restart: always
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 8080:8080
