version: "3.7"
services:
  db:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_DB=altruisto
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=altruistoPassword
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/:/docker-entrypoint-initdb.d/
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - .:/var/www/html
    links:
      - db
    env_file:
      - .env
    user: 1000:1000
  composer:
    image: composer
    volumes:
      - .:/app
    command: install --ignore-platform-reqs
  nginx:
    image: nginx:1.15.3-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 8000:80
    restart: always
    depends_on:
      - php
      - db
  adminer:
    image: adminer
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - 8080:8080
